Todo list
firstpj/React-to-do-list pull request #1
Opened 2023-08-22 14:37 UTC by firstpj

Created a feature branch.
 Setup React environment using vite. 
Created the to-do list…

2023-08-22 20:19 UTC, tajemouti requested changes
## Hi @firstpj

Good job so far!
There is an issue that you still need to work on but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Correct Gitflow ✅ 
- No linters errors✅ 
- The application works correctly ✅ 
- The application uses components ✅ 
- The application uses props and state ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @tajemouti in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 20:19 UTC, tajemouti commented on README.md
> +- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
Kindly edit the README file to include the project details. A Professional README file is essential to explain what is uploaded and how we can install or use it.

2023-08-22 20:28 UTC, firstpj commented
Thank you for the review. The require changes is noted.

On Tue, 22 Aug 2023, 8:19 PM Ajrass Tajemouti ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @firstpj <https://github.com/firstpj>
>
> Good job so far!
> There is an issue that you still need to work on but you are almost there!
> STATUS: REQUIRE CHANGES 🔴
>
>
> <https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966>
> Highlights
>
>    - Correct Gitflow ✅
>    - The application is working correctly ✅
>    - The application is using components ✅
>    - The application is using props and state ✅
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers, and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag @tajemouti <https://github.com/tajemouti> in your
> question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/firstpj/React-to-do-list/pull/1#discussion_r1302140278>
> :
>
> > -# React-to-do-list
> \ No newline at end of file
> +# React + Vite
> +
> +This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.
> +
> +Currently, two official plugins are available:
> +
> +- ***@***.***/plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md) uses [Babel](https://babeljs.io/) for Fast Refresh
> +- ***@***.***/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh
>
> Kindly edit the README file to include the project details. A Professional
> README file is essential to explain what is uploaded and how we can install
> or use it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/firstpj/React-to-do-list/pull/1#pullrequestreview-1590246986>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MQM5UAKEECPFWOQX3JNI3XWUH6XANCNFSM6AAAAAA32BCFV4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-22 22:15 UTC, tajemouti approved these changes
# Approved :green_circle: 
Hi @firstpj, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application works as expected :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Implemented all the required changes :white_check_mark:   

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 22:19 UTC, merged

2023-08-29 18:21 UTC, firstpj commented
Awesome, thank you so much!

On Tue, 22 Aug 2023, 10:15 PM Ajrass Tajemouti ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Approved 🟢
>
> Hi @firstpj <https://github.com/firstpj>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif>
> Highlights ✔️
>
>    - Good UI design ✅
>    - Application works as expected ✅
>    - Git flow is used correctly ✅
>    - Implemented all the required changes ✅
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/firstpj/React-to-do-list/pull/1#pullrequestreview-1590418396>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MQM5XX554BNOH4RLABGT3XWUVQ3ANCNFSM6AAAAAA32BCFV4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-29 18:22 UTC, firstpj commented
https://microverse.zoom.us/j/95543253837?pwd=eXFUdUVJWFRRQWFsTkRVK1FuSWpLQT09

On Tue, Aug 29, 2023 at 7:22 PM Collins Akorda ***@***.***>
wrote:

> Awesome, thank you so much!
>
> On Tue, 22 Aug 2023, 10:15 PM Ajrass Tajemouti ***@***.***>
> wrote:
>
>> ***@***.**** approved this pull request.
>> Approved 🟢
>>
>> Hi @firstpj <https://github.com/firstpj>,
>>
>> Your project is complete! There is nothing else to say other than... it's
>> time to merge it [image: :shipit:]
>> Congratulations! 🎉
>>
>>
>> <https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif>
>> Highlights ✔️
>>
>>    - Good UI design ✅
>>    - Application works as expected ✅
>>    - Git flow is used correctly ✅
>>    - Implemented all the required changes ✅
>>
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
>> PR. However, I strongly recommend you to take them into account as they can
>> make your code better. Some of them were simply missed by the previous
>> reviewer and addressing them will really improve your application.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/firstpj/React-to-do-list/pull/1#pullrequestreview-1590418396>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A3MQM5XX554BNOH4RLABGT3XWUVQ3ANCNFSM6AAAAAA32BCFV4>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-08-29 18:25 UTC, firstpj commented
https://microverse.zoom.us/j/95543253837?pwd=eXFUdUVJWFRRQWFsTkRVK1FuSWpLQT09

On Tue, Aug 29, 2023 at 7:22 PM Collins Akorda ***@***.***>
wrote:

>
> https://microverse.zoom.us/j/95543253837?pwd=eXFUdUVJWFRRQWFsTkRVK1FuSWpLQT09
>
> On Tue, Aug 29, 2023 at 7:22 PM Collins Akorda ***@***.***>
> wrote:
>
>> Awesome, thank you so much!
>>
>> On Tue, 22 Aug 2023, 10:15 PM Ajrass Tajemouti ***@***.***>
>> wrote:
>>
>>> ***@***.**** approved this pull request.
>>> Approved 🟢
>>>
>>> Hi @firstpj <https://github.com/firstpj>,
>>>
>>> Your project is complete! There is nothing else to say other than...
>>> it's time to merge it [image: :shipit:]
>>> Congratulations! 🎉
>>>
>>>
>>> <https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif>
>>> Highlights ✔️
>>>
>>>    - Good UI design ✅
>>>    - Application works as expected ✅
>>>    - Git flow is used correctly ✅
>>>    - Implemented all the required changes ✅
>>>
>>> Optional suggestions
>>>
>>> *Every comment with the [OPTIONAL] prefix won't stop the approval of
>>> this PR. However, I strongly recommend you to take them into account as
>>> they can make your code better. Some of them were simply missed by the
>>> previous reviewer and addressing them will really improve your application.*
>>>
>>> Cheers and Happy coding!👏👏👏
>>>
>>> Feel free to leave any questions or comments in the PR thread if
>>> something is not 100% clear.
>>> Please, remember to tag me in your question so I can receive the
>>> notification.
>>> ------------------------------
>>>
>>> *As described in the Code reviews limits policy
>>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>>> limited number of reviews per project (check the exact number in your
>>> Dashboard). If you think that the code review was not fair, you can request
>>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/firstpj/React-to-do-list/pull/1#pullrequestreview-1590418396>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/A3MQM5XX554BNOH4RLABGT3XWUVQ3ANCNFSM6AAAAAA32BCFV4>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>

2023-08-29 19:08 UTC, firstpj commented
https://microverse.zoom.us/j/97530658650?pwd=UTlnSGlwbGhVaitMTnh2MXZDNmIzQT09

On Tue, Aug 29, 2023 at 7:25 PM Collins Akorda ***@***.***>
wrote:

>
> https://microverse.zoom.us/j/95543253837?pwd=eXFUdUVJWFRRQWFsTkRVK1FuSWpLQT09
>
> On Tue, Aug 29, 2023 at 7:22 PM Collins Akorda ***@***.***>
> wrote:
>
>>
>> https://microverse.zoom.us/j/95543253837?pwd=eXFUdUVJWFRRQWFsTkRVK1FuSWpLQT09
>>
>> On Tue, Aug 29, 2023 at 7:22 PM Collins Akorda ***@***.***>
>> wrote:
>>
>>> Awesome, thank you so much!
>>>
>>> On Tue, 22 Aug 2023, 10:15 PM Ajrass Tajemouti ***@***.***>
>>> wrote:
>>>
>>>> ***@***.**** approved this pull request.
>>>> Approved 🟢
>>>>
>>>> Hi @firstpj <https://github.com/firstpj>,
>>>>
>>>> Your project is complete! There is nothing else to say other than...
>>>> it's time to merge it [image: :shipit:]
>>>> Congratulations! 🎉
>>>>
>>>>
>>>> <https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif>
>>>> Highlights ✔️
>>>>
>>>>    - Good UI design ✅
>>>>    - Application works as expected ✅
>>>>    - Git flow is used correctly ✅
>>>>    - Implemented all the required changes ✅
>>>>
>>>> Optional suggestions
>>>>
>>>> *Every comment with the [OPTIONAL] prefix won't stop the approval of
>>>> this PR. However, I strongly recommend you to take them into account as
>>>> they can make your code better. Some of them were simply missed by the
>>>> previous reviewer and addressing them will really improve your application.*
>>>>
>>>> Cheers and Happy coding!👏👏👏
>>>>
>>>> Feel free to leave any questions or comments in the PR thread if
>>>> something is not 100% clear.
>>>> Please, remember to tag me in your question so I can receive the
>>>> notification.
>>>> ------------------------------
>>>>
>>>> *As described in the Code reviews limits policy
>>>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>>>> limited number of reviews per project (check the exact number in your
>>>> Dashboard). If you think that the code review was not fair, you can request
>>>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>>>
>>>> —
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/firstpj/React-to-do-list/pull/1#pullrequestreview-1590418396>,
>>>> or unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/A3MQM5XX554BNOH4RLABGT3XWUVQ3ANCNFSM6AAAAAA32BCFV4>
>>>> .
>>>> You are receiving this because you were mentioned.Message ID:
>>>> ***@***.***>
>>>>
>>>